_target_: src.models.ecg_module.ECGLitModule
num_classes: 2
learning_rate: 0.001
compile: false

net:
  _target_: src.models.components.mcdann_net.MCDANNNet
  channels:
    _target_: torch.nn.ModuleList
    modules:
      - _target_: src.models.components.mcdann_net.DACB
      - _target_: src.models.components.mcdann_net.DACB
      - _target_: src.models.components.mcdann_net.DACB
      - _target_: src.models.components.mcdann_net.DACB
      - _target_: src.models.components.mcdann_net.DACB
      - _target_: src.models.components.mcdann_net.DACB
      - _target_: src.models.components.mcdann_net.DACB
      - _target_: src.models.components.mcdann_net.DACB
      - _target_: src.models.components.mcdann_net.DACB
      - _target_: src.models.components.mcdann_net.DACB
      - _target_: src.models.components.mcdann_net.DACB
      - _target_: src.models.components.mcdann_net.DACB

  positional_encoding:
    _target_: src.models.components.mcdann_net.PositionalEncoding
    d_model: 64
    max_seq_length: 12

  multi_attention:
    _target: torch.nn.MultiheadAttention
    embed_dim: 64
    num_heads: 1
    dropout: 0.1
    batch_first: true

  classifier: # Linear -> BN -> LR -> Dropout
    _target: nn.Sequential
    _args_:
      - _target_: torch.nn.Linear
        in_features: 768 # 64 * 12
        out_features: 256

      - _target_: torch.nn.BatchNorm1d
        num_features: 256

      - _target_: torch.nn.LeakyReLU
        negative_slope: 0.01

      - _target_: torch.nn.Dropout
        p: 0.5

      - _target_: torch.nn.Linear
        in_features: 256
        out_features: 128

      - _target_: torch.nn.BatchNorm1d
        num_features: 128

      - _target_: torch.nn.LeakyReLU
        negative_slope: 0.01

      - _target_: torch.nn.Dropout
        p: 0.5

      - _target_: torch.nn.Linear
        in_features: 256
        out_features: 2

  num_classes: 2
